<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SunilNad_Lenevo330" ignored="0" name="FirefoxTest" tests="5" failures="1" timestamp="2021-07-01T20:06:17 IST" time="23.875" errors="0">
  <testcase name="method2" time="0.959" classname="tests.Test1"/>
  <testcase name="method5" time="1.377" classname="tests.Test1"/>
  <testcase name="method3" time="1.464" classname="tests.Test1"/>
  <testcase name="method1" time="2.057" classname="tests.Test1">
    <failure type="java.lang.AssertionError" message="failing... ">
      <![CDATA[java.lang.AssertionError: failing... 
at tests.Test1.method1(Test1.java:21)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase name="method4" time="0.913" classname="tests.Test1"/>
</testsuite> <!-- FirefoxTest -->
